
import type { Flight, Hotel } from './types';

export const placeholderFlights: Flight[] = [
  {
    id: 'FL001',
    airline: 'SkyHigh Airlines',
    airlineLogoUrl: 'https://placehold.co/40x40.png',
    flightNumber: 'SH203',
    from: 'New York (JFK)',
    to: 'London (LHR)',
    departureTime: '2024-09-15T18:00:00Z',
    arrivalTime: '2024-09-16T06:00:00Z',
    duration: '7h 0m',
    price: 550,
    stops: 0,
    departureAirport: 'John F. Kennedy International Airport',
    arrivalAirport: 'London Heathrow Airport',
    aircraftType: 'Boeing 777',
    amenities: ['In-flight Wi-Fi', 'Meals included', 'Entertainment System'],
  },
  {
    id: 'FL002',
    airline: 'Horizon Wings',
    airlineLogoUrl: 'https://placehold.co/40x40.png',
    flightNumber: 'HW789',
    from: 'Paris (CDG)',
    to: 'Tokyo (NRT)',
    departureTime: '2024-10-20T14:30:00Z',
    arrivalTime: '2024-10-21T09:30:00Z',
    duration: '12h 0m',
    price: 820,
    stops: 1,
    departureAirport: 'Charles de Gaulle Airport',
    arrivalAirport: 'Narita International Airport',
    aircraftType: 'Airbus A350',
    amenities: ['Extra Legroom Option', 'Meals included'],
  },
  {
    id: 'FL003',
    airline: 'Oceanic Air',
    airlineLogoUrl: 'https://placehold.co/40x40.png',
    flightNumber: 'OA415',
    from: 'Los Angeles (LAX)',
    to: 'Sydney (SYD)',
    departureTime: '2024-11-05T22:00:00Z',
    arrivalTime: '2024-11-07T06:00:00Z',
    duration: '15h 0m',
    price: 1200,
    stops: 0,
    departureAirport: 'Los Angeles International Airport',
    arrivalAirport: 'Sydney Kingsford Smith Airport',
    aircraftType: 'Boeing 787 Dreamliner',
    amenities: ['Flat-bed seats (Business)', 'Premium Dining', 'In-flight Wi-Fi'],
  },
];

export const placeholderHotels: Hotel[] = [
  {
    id: 'HT001',
    name: 'The Grand Plaza',
    location: 'London, UK',
    rating: 5,
    pricePerNight: 250,
    thumbnailUrl: 'https://placehold.co/300x200.png',
    thumbnailHint: 'luxury hotel facade',
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    imageHints: ['elegant hotel lobby', 'modern suite interior'],
    amenities: ['Free Wi-Fi', 'Swimming Pool', 'Gym', 'Restaurant', 'Spa'],
    description: 'Experience luxury at The Grand Plaza, located in the heart of London. Enjoy world-class amenities and breathtaking city views.',
    checkInTime: '15:00',
    checkOutTime: '11:00',
    roomTypes: [
      { name: 'Standard Room', price: 250, features: ['Queen Bed', 'City View'] },
      { name: 'Deluxe Suite', price: 400, features: ['King Bed', 'Balcony', 'Jacuzzi'] },
    ]
  },
  {
    id: 'HT002',
    name: 'Sakura Inn Tokyo',
    location: 'Tokyo, Japan',
    rating: 4,
    pricePerNight: 180,
    thumbnailUrl: 'https://placehold.co/300x200.png',
    thumbnailHint: 'traditional japanese inn',
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    imageHints: ['serene japanese garden', 'tatami room zen'],
    amenities: ['Free Wi-Fi', 'Onsen (Hot Spring)', 'Traditional Breakfast', 'Garden'],
    description: 'Immerse yourself in Japanese culture at Sakura Inn Tokyo. Featuring traditional tatami rooms and a serene onsen.',
    checkInTime: '16:00',
    checkOutTime: '10:00',
     roomTypes: [
      { name: 'Tatami Room', price: 180, features: ['Futon Beds', 'Garden View'] },
      { name: 'Western Style Room', price: 220, features: ['Twin Beds', 'City View'] },
    ]
  },
  {
    id: 'HT003',
    name: 'Sunset Beach Resort',
    location: 'Sydney, Australia',
    rating: 4,
    pricePerNight: 220,
    thumbnailUrl: 'https://placehold.co/300x200.png',
    thumbnailHint: 'tropical beach resort',
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    imageHints: ['infinity pool ocean', 'beachfront bungalow sunset'],
    amenities: ['Beach Access', 'Outdoor Pool', 'Restaurant', 'Bar', 'Water Sports'],
    description: 'Relax and unwind at Sunset Beach Resort, offering stunning ocean views and direct access to Sydney\'s famous beaches.',
    checkInTime: '14:00',
    checkOutTime: '12:00',
    roomTypes: [
      { name: 'Ocean View Room', price: 220, features: ['King Bed', 'Balcony'] },
      { name: 'Family Bungalow', price: 350, features: ['2 Bedrooms', 'Kitchenette'] },
    ]
  },
];
