
import type { Flight, Hotel, Property } from './types';

const newDefaultHotelImage = 'https://media.istockphoto.com/id/1197480605/photo/3d-render-of-luxury-hotel-lobby-and-reception.jpg?s=612x612&w=0&k=20&c=h2DMumrFFZDGqPypcK4Whx8mM1EdCKWh8PLY2saLIzo=';
const newDefaultHotelHint = 'hotel lobby';

export const placeholderFlights: Flight[] = [
  {
    id: 'FL001',
    airline: 'SkyHigh Airlines',
    airlineLogoUrl: 'https://placehold.co/40x40.png',
    flightNumber: 'SH203',
    from: 'New York (JFK)',
    to: 'London (LHR)',
    departureTime: '2024-09-15T18:00:00Z',
    arrivalTime: '2024-09-16T06:00:00Z',
    duration: '7h 0m',
    price: 550,
    stops: 0,
    departureAirport: 'John F. Kennedy International Airport',
    arrivalAirport: 'London Heathrow Airport',
    aircraftType: 'Boeing 777',
    amenities: ['In-flight Wi-Fi', 'Meals included', 'Entertainment System'],
  },
  {
    id: 'FL002',
    airline: 'Horizon Wings',
    airlineLogoUrl: 'https://placehold.co/40x40.png',
    flightNumber: 'HW789',
    from: 'Paris (CDG)',
    to: 'Tokyo (NRT)',
    departureTime: '2024-10-20T14:30:00Z',
    arrivalTime: '2024-10-21T09:30:00Z',
    duration: '12h 0m',
    price: 820,
    stops: 1,
    departureAirport: 'Charles de Gaulle Airport',
    arrivalAirport: 'Narita International Airport',
    aircraftType: 'Airbus A350',
    amenities: ['Extra Legroom Option', 'Meals included'],
  },
  {
    id: 'FL003',
    airline: 'Oceanic Air',
    airlineLogoUrl: 'https://placehold.co/40x40.png',
    flightNumber: 'OA415',
    from: 'Los Angeles (LAX)',
    to: 'Sydney (SYD)',
    departureTime: '2024-11-05T22:00:00Z',
    arrivalTime: '2024-11-07T06:00:00Z',
    duration: '15h 0m',
    price: 1200,
    stops: 0,
    departureAirport: 'Los Angeles International Airport',
    arrivalAirport: 'Sydney Kingsford Smith Airport',
    aircraftType: 'Boeing 787 Dreamliner',
    amenities: ['Flat-bed seats (Business)', 'Premium Dining', 'In-flight Wi-Fi'],
  },
];

export const placeholderHotels: Hotel[] = [
  {
    id: 'HT001',
    name: 'The Grand Plaza',
    location: 'London, UK',
    rating: 5,
    pricePerNight: 250,
    thumbnailUrl: newDefaultHotelImage,
    thumbnailHint: newDefaultHotelHint,
    images: [
        newDefaultHotelImage,
        'https://cdn.pixabay.com/photo/2016/12/04/19/20/london-1882046_1280.jpg'
    ],
    imageHints: [newDefaultHotelHint, 'london city night'],
    amenities: ['Free Wi-Fi', 'Swimming Pool', 'Gym', 'Restaurant', 'Spa'],
    description: 'Experience luxury at The Grand Plaza, located in the heart of London. Enjoy world-class amenities and breathtaking city views.',
    checkInTime: '15:00',
    checkOutTime: '11:00',
    roomTypes: [
      { name: 'Standard Room', price: 250, features: ['Queen Bed', 'City View'] },
      { name: 'Deluxe Suite', price: 400, features: ['King Bed', 'Balcony', 'Jacuzzi'] },
    ],
    ownerEmail: 'super.admin@example.com', // Or a generic super admin email
    isApproved: true,
  },
  {
    id: 'HT002',
    name: 'Sakura Inn Tokyo',
    location: 'Tokyo, Japan',
    rating: 4,
    pricePerNight: 180,
    thumbnailUrl: newDefaultHotelImage,
    thumbnailHint: newDefaultHotelHint,
    images: [
        newDefaultHotelImage,
        'https://cdn.pixabay.com/photo/2016/10/18/10/58/japan-1749764_1280.jpg'
    ],
    imageHints: [newDefaultHotelHint, 'kyoto temple autumn'],
    amenities: ['Free Wi-Fi', 'Onsen (Hot Spring)', 'Traditional Breakfast', 'Garden'],
    description: 'Immerse yourself in Japanese culture at Sakura Inn Tokyo. Featuring traditional tatami rooms and a serene onsen.',
    checkInTime: '16:00',
    checkOutTime: '10:00',
     roomTypes: [
      { name: 'Tatami Room', price: 180, features: ['Futon Beds', 'Garden View'] },
      { name: 'Western Style Room', price: 220, features: ['Twin Beds', 'City View'] },
    ],
    ownerEmail: 'bob@example.com', // Assuming bob@example.com is a hotel owner
    isApproved: true,
  },
  {
    id: 'HT003',
    name: 'Sunset Beach Resort',
    location: 'Sydney, Australia',
    rating: 4,
    pricePerNight: 220,
    thumbnailUrl: newDefaultHotelImage,
    thumbnailHint: newDefaultHotelHint,
    images: [
        newDefaultHotelImage,
        'https://cdn.pixabay.com/photo/2018/01/28/22/19/sunset-3114992_1280.jpg'
    ],
    imageHints: [newDefaultHotelHint, 'beach sunset chairs'],
    amenities: ['Beach Access', 'Outdoor Pool', 'Restaurant', 'Bar', 'Water Sports'],
    description: 'Relax and unwind at Sunset Beach Resort, offering stunning ocean views and direct access to Sydney\'s famous beaches.',
    checkInTime: '14:00',
    checkOutTime: '12:00',
    roomTypes: [
      { name: 'Ocean View Room', price: 220, features: ['King Bed', 'Balcony'] },
      { name: 'Family Bungalow', price: 350, features: ['2 Bedrooms', 'Kitchenette'] },
    ],
    ownerEmail: 'super.admin@example.com',
    isApproved: true,
  },
];

export const placeholderProperties: Property[] = [
  {
    id: 'PROP001',
    title: 'Sunny Downtown Apartment with Balcony',
    type: 'Entire apartment',
    location: 'Lisbon, Portugal',
    pricePerNight: 120,
    rating: 4.8,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'Washer', 'Hair dryer'],
    thumbnailUrl: 'https://placehold.co/600x400.png',
    thumbnailHint: 'apartment interior',
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    imageHints: ['apartment living room', 'apartment bedroom'],
    hostName: 'Maria S.',
    hostAvatarUrl: 'https://placehold.co/50x50.png',
    hostAvatarHint: 'woman portrait',
    isSuperhost: true,
  },
  {
    id: 'PROP002',
    title: 'Cozy Cabin Getaway in the Woods',
    type: 'Entire cabin',
    location: 'Asheville, North Carolina, USA',
    pricePerNight: 150,
    rating: 4.9,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Kitchen', 'Indoor fireplace', 'Hot tub', 'Free parking'],
    thumbnailUrl: 'https://placehold.co/600x400.png',
    thumbnailHint: 'cabin exterior woods',
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    imageHints: ['cabin living room fireplace', 'cabin bedroom cozy'],
    hostName: 'David K.',
    hostAvatarUrl: 'https://placehold.co/50x50.png',
    hostAvatarHint: 'man portrait',
    isSuperhost: true,
  },
  {
    id: 'PROP003',
    title: 'Chic Studio near Eiffel Tower',
    type: 'Entire studio',
    location: 'Paris, France',
    pricePerNight: 180,
    rating: 4.7,
    guests: 2,
    bedrooms: 0, // Studio
    beds: 1,
    baths: 1,
    amenities: ['Wifi', 'Kitchenette', 'Elevator', 'City view'],
    thumbnailUrl: 'https://placehold.co/600x400.png',
    thumbnailHint: 'paris studio apartment',
    images: ['https://placehold.co/600x400.png'],
    imageHints: ['studio interior modern'],
    hostName: 'Sophie L.',
    isSuperhost: false,
  },
  {
    id: 'PROP004',
    title: 'Spacious Beach House with Ocean View',
    type: 'Entire house',
    location: 'Malibu, California, USA',
    pricePerNight: 350,
    rating: 4.95,
    guests: 8,
    bedrooms: 4,
    beds: 5,
    baths: 3,
    amenities: ['Wifi', 'Kitchen', 'Beachfront', 'Pool', 'BBQ grill', 'Free parking'],
    thumbnailUrl: 'https://placehold.co/600x400.png',
    thumbnailHint: 'beach house exterior',
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    imageHints: ['beach house living room ocean', 'beach house bedroom view', 'beach house pool deck'],
    hostName: 'Michael B.',
    hostAvatarUrl: 'https://placehold.co/50x50.png',
    hostAvatarHint: 'man portrait casual',
    isSuperhost: true,
  },
];
